Repository vmware/terraform-provider-vra7, pull requests merged in 2019-05, with the labels that each got.

#1 Update main.go import path
  main.go
Labels: size/XS

#2 Add required scripts/
  scripts/changelog-links.sh
  scripts/errcheck.sh
  scripts/gofmtcheck.sh
  scripts/gogetcookie.sh
Labels: size/M

#4 Provider Release Process
  GNUmakefile
  Makefile
  go.mod
  go.sum
  main.go
  scripts/changelog-links.sh
  scripts/errcheck.sh
  scripts/gofmtcheck.sh
  scripts/gogetcookie.sh
  sdk/client_utils.go
  sdk/vra7_sdk.go
  vra7/provider.go
  vra7/resource_vra7_deployment.go
Labels: size/L

#5 Update go.mod and go.sum for building in new repo
  go.mod
  go.sum
Labels: size/L

#6 Switch to terraform-providers repo
  README.md
  go.mod
  go.sum
  sdk/vra7_sdk_test.go
  vra7/provider_test.go
  vra7/resource_vra7_deployment_test.go
  website/docs/index.html.markdown
  website/docs/r/deployment.html.markdown
Labels: documentation, size/M

#10 Fix travis tests and changes to pass linting
  .golangci.yml
  GNUmakefile
  vra7/provider_test.go
  vra7/resource_vra7_deployment.go
  vra7/resource_vra7_deployment_test.go
Labels: size/S

#11 Formatting example code and removing debugging comment
  website/docs/index.html.markdown
Labels: documentation, size/XS
