Repository vmware/terraform-provider-vra7, pull requests merged in 2020-04, with the labels that each got.

#40 Modify read deployment to read all the properties of the resource
  CHANGELOG.md
  README.md
  example/multi-machine/main.tf
  example/multi-machine/terraform.tfvars.sample
  example/multi-machine/variables.tf
  example/multi-machine/versions.tf
  example/remote-execute/main.tf
  example/simple/main.tf
  go.mod
  scripts/update_resource_state.sh
  sdk/mock_data_test.go
  sdk/schema.go
  sdk/vra7_sdk.go
  sdk/vra7_sdk_test.go
  utils/utilities.go
  utils/utilities_test.go
  vra7/data_source_vra7_deployment.go
  vra7/provider.go
  vra7/resource_configuration.go
  vra7/resource_vra7_deployment.go
  vra7/resource_vra7_deployment_test.go
  website/docs/d/vra7_deployment.html.markdown
  website/docs/r/deployment.html.markdown
Labels: bug, documentation, enhancement, feature request, size/XXL

#34 Enable request/response logging
  sdk/vra7_client.go
Labels: size/XS

#62 Fix for issues # 59 and 60, reading cluster value in the state file
  sdk/vra7_sdk.go
  vra7/data_source_vra7_deployment.go
  vra7/resource_configuration.go
  vra7/resource_vra7_deployment.go
Labels: size/M

#63 Update Change log
  CHANGELOG.md
Labels: size/XS
